### ISSUE TITLE
gpu训练报错 CPU->GPU Memcpy failed Aborted

### ISSUE THREAD

**Issue by Dengyingjie** [alibaba/nann#11]
A10的卡，这是oom了么

**Comment by Dengyingjie** [comment]
解决了，版本问题，A10只支持cuda11. 换gpu可以。
所以请问有支持cuda11的版本镜像吗。。。

**Comment by bl0** [comment]
目前我们没有开源的cuda11的镜像，可以参考 https://github.com/alibaba/nann/blob/master/NANN_impls/docker/Dockerfile 这里的dockerfile 自己build一下。
