### ISSUE TITLE
BlazeXlaOp为什么用异步实现？是否有性能问题？

### ISSUE THREAD

**Issue by striveth** [alibaba/nann#13]
如题，BlazeXlaOp异步实现在并发量比较大的情况下，耗时比较高，为什么不用同步的方式实现？

**Comment by bl0** [comment]
感谢提问，这是一个很有深度的问题。
我们采用异步模式是因为这样资源效率更高一些，同样资源情况下可以容纳更高的QPS。但是，正如你所说，现有异步模式确实存在并发高的情况下后面几个BlazeXlaOp排队导致的P99 RT上涨的情况。这个问题我们最近也遇到了，最终通过优先级队列的方式（提高后面几个BlazeXlaOp在调度队列中的优先级）降低了P99 RT，缓解了这个问题。

**Comment by striveth** [comment]
感谢回答，你们有对比同步和异步调用的资源和性能的数据吗？
我们现在遇到一个问题，并发高的时候超时率比较高，但是资源的利用率并不高。

**Comment by bl0** [comment]
我们没有开发过同步调用的版本。

性能和资源利用率方面，和机器性能有比较大的关系。在我们目前的场景下，给定attention+mlp交叉的复杂模型，T4单机单卡能做到600 qps，四次打分总量大概3w，p99 latency 20ms内，符合我们自己的业务需求。

建议可以打印timeline分析下性能瓶颈。
