### ISSUE TITLE
GPU多流并行计算是怎么实现的？

### ISSUE THREAD

**Issue by striveth** [alibaba/nann#14]
"Runtime Optimization -- We support GPU Multi-Streaming with Multi-Contexts, which greatly enhances parallelism."
问下这里是怎么实现的？要使用的话需要怎么配置？

**Comment by Chris19920210** [comment]
1、具体实现逻辑可参考这个commit：https://github.com/alibaba/nann/commit/8f72f9afbf4ea8cf67236caa519deb4965e8ae9d
2、配置可参考：https://github.com/alibaba/nann/blob/master/NANN_impls/nann/benchmark/config_proto

实现逻辑就是通过multi-context实现multi-streaming，相当于模型会有多个实例，显存会有一定膨胀。这个功能的开启不一定能带来性能收益，需要看你的在线inference模型是否是kernel launch bound，如果是，那预期是有效的。
