### ISSUE TITLE
Wrong `top_k` used for index start_level

### ISSUE THREAD

**Issue by neosunhan** [alibaba/nann#16]
In the `Model.retrieval` function:

```
results, scores = self.top_k(results, scores, self.top_k_per_level[0])
```

This line of code gets the top k nodes in the start_level. However, it uses the `top_k` value for level 0 instead of the start level (default=2).

It seems like it should be changed to:

```
results, scores = self.top_k(results, scores, self.top_k_per_level[self.start_level])
```

**Comment by bl0** [comment]
Thanks for your issue. I have fixed the bug in https://github.com/alibaba/nann/commit/e0bcbda33cd13311bf8b0a7d7c6c5ae6e1670c22.
