### ISSUE TITLE
nann/util.py中的fast_argtopk实现有问题

### ISSUE THREAD

**Issue by YuhwaChoong** [alibaba/nann#2]
现在的实现为：
```
def fast_argtopk(arr, k):
  indices = np.argpartition(-arr, k)[:k]
  return indices[np.argsort(arr[indices])]
```
返回值index是按照score升序排列，在后面取topN时并非全局topN，而是[k-N,K]，在test中存在多个topk-eval时测试结果不合预期。
应在返回index时仍降序排列，改为：
```
def fast_argtopk(arr, k):
  indices = np.argpartition(-arr, k)[:k]
  return indices[np.argsort(-arr[indices])]
```

**Comment by bl0** [comment]
感谢提醒，现在的实现确实是错的，已在commit https://github.com/alibaba/nann/commit/da6c28dbbb56d1a0bd7e3e28f7e0027ac9f27894 中修复。
