### ISSUE TITLE
为什么build_opt_graph.py发布模型使用了多个自定义算子?

### ISSUE THREAD

**Issue by ambjlon** [alibaba/nann#3]
build_opt_graph.py生成的模型是要最终在线服务使用的吧
为什么build_opt_graph.py里面使用了很多自定义算子, 比如bitmap_ref_difference, group_gather等
在model.py中实现的test功能, 也要实现和build_opt_graph.py中类似的hnsw搜索逻辑, 但是model.py中的test确没有使用bitmap_ref_difference这些自定义ops, 而是直接使用的TensorFlow的原生op, 比如tf.sets.set_difference.
这是为什么呢, 是因为在线模型打分不使用bitmap_ref_difference这些算子会有性能问题吗?

**Comment by Chris19920210** [comment]
对的，在线不使用Custom Ops会有性能问题，比如TF 原生的Set相关的Op，在这个场景下就会性能较差，使用bitmap_ref_difference，在内存重复利用以及集合相关操作的效率上都有些优势。离线用TF原生Ops主要是为了灵活迭代，对于效率的要求没有那么高。
