### ISSUE TITLE
好像只支持Item2Item的检索，支持User2Item的检索吗？

### ISSUE THREAD

**Issue by treper** [alibaba/nann#5]
文档给的只有导出item embedding然后检索的例子，如果是双塔模型比如DSSM如何serving？另外如果要搜索指定的item池子，但query item的scope是全量，这个要怎么实现？

**Comment by bl0** [comment]
1. 我们提供的就是user2item的检索哈。请详细查看论文和文档的介绍。
2. 分库检索的能力我们没有开源出来，可以自行开发。大致实现是在构建索引的时候把item embedding分库，并分别构建索引，在检索的时候到特定的索引里检索。

**Comment by treper** [comment]
给定的docker可以只用cpu的机器serving吗？

**Comment by bl0** [comment]
因为serving过程中需要复杂模型打分，因此如果只用cpu的话在线效率会很低。

**Comment by treper** [comment]
> 1. 我们提供的就是user2item的检索哈。请详细查看论文和文档的介绍。
> 2. 分库检索的能力我们没有开源出来，可以自行开发。大致实现是在构建索引的时候把item embedding分库，并分别构建索引，在检索的时候到特定的索引里检索。

分库索引是改这个build_hnsw_index.py文件吗？
另外例子用的数据UserBehavior.csv是id化之后的，实际生产使用也是id化后训练，搜素结果再映射回来吗？还是会用hash的方式？

**Comment by bl0** [comment]
1. 是的
2. 生产过程也是会使用item在embedding里的下标作为id，检索结束后将该id映射回item id。

**Comment by ComingToy** [comment]
是不是可以这样做：
1. 训练完成了导出item_embedding，写入faiss中
2. 线上infer的时候通过enter points输入模型进行graph的forward，拿到结果取topk items
3. topk items拼接user特征再进行forward 拿到下一批topk items

上述的实现本质上跟目前nann是一样的？只是nann把faiss检索的逻辑放到了graph里面去实现了？

**Comment by bl0** [comment]
功能上是差不多的。但是都用tensorflow graph来实现的话在线serving的效率会高很多。

**Comment by bl0** [comment]
I am closing this issue due to a long time of inactivity, feel free to reopen it if there is any question. Thanks!
