### ISSUE TITLE
如果候选集有500万items, 那么需要模型打分10万次?

### ISSUE THREAD

**Issue by ambjlon** [alibaba/nann#6]
请问, 这个二向箔召回实现的候选集是多大呢?
如果是500万, 每次请求需要给10万个item打分(看介绍说2%打分量, hnsw准确率95%), 这个计算量还是非常大的吧, 即便是很简单的模型, 耗时能搞定?

**Comment by bl0** [comment]
hi，这个问题很关键，2%打分量是我们在百万量级的时候的比例。
但是我们后续也在千万量级的候选集上运行过，也是没问题的（大概数字：打分量20k，hnsw检索精度90%）。
