### ISSUE TITLE
无法部署模型

### ISSUE THREAD

**Issue by ta0yu** [alibaba/nann#7]
hi，我尝试跑通流程，发现无法找到部署模型时使用的docker镜像alibaba/nann_serving，请问如何下载

**Comment by bl0** [comment]
该镜像托管在docker hub官方网站上，请确保部署机器能访问外网：
https://hub.docker.com/repository/docker/alinann/nann_serving

**Comment by ta0yu** [comment]
成功下载了，谢谢🙏

**Comment by HuBlanker** [comment]
hi, 我在尝试readme中的流程.
